name: beyond_cli
description: A simple command line interface, for initializing Fullstack flutter project (Beyond)
version: 1.0.0
homepage: https://github.com/Meruya-Techhnology/Beyond/tree/main/beyond_cli

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  beyond: main